#!/usr/bin/env bash
# displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
n=1
while (( n <= 10))
do
echo "Best School"
if ((n == 9))
then
echo "Best School"
echo "Hi"
fi
((n++))
done

