#!/usr/bin/env bash
# script that loops from 1 - 10 and do certain elifs
n=1
while ((n <= 10))
do
if ((n == 4))
then
echo "bad luck"
elif ((n == 8))
then
echo "good luck"
else
echo "Best School"
fi
((n++))
done
